<div class="panel-pane pane-entity-field pane-node-field-body-no-summary">
	<div class="pane-content">
		<div class="field field-name-field-body-no-summary field-type-text-long field-label-hidden">
			<div class="field-items">
				<div class="field-item even">
					<h3>Variable settings</h3>

					<p class="p1"> Go to <strong>DocuSIGN CustomFields | Custom Variable Settings</strong></p>

					<h3 class="p1">Please use following variables in setting</h3>
					<p></p>
					<h3 class="p1"></h3>


					<ul style="margin-left: 20px;">
						<li><span style="font-weight:bold;color:black;">accountno : </span>  It will return the customer account number</li>
						<li><span style="font-weight:bold;color:black;">address :</span>  It will return the customer address</li>
						<li><span style="font-weight:bold;color:black;"> company :</span> It will return the customer company name</li>
						<li><span style="font-weight:bold;color:black;">contactname :</span>  It will return the customer name</li>
						<li><span style="font-weight:bold;color:black;">email :</span>  It will return the customer email address</li>
						<li><span style="font-weight:bold;color:black;">orderid :</span>  It will return the order id </li>
						<li><span style="font-weight:bold;color:black;">items :</span>  It will return the order items </li>
						<li><span style="font-weight:bold;color:black;">phone :</span>  It will return the customer contact number</li>
						<li><span style="font-weight:bold;color:black;">orderdate :</span>  It will return the order date</li>
					</ul>
					<h3>Note: Only use these variable in text box other wise your data will not reflect in DocuSIGN document.</h3>
				</div>
			</div>
		</div>  
	</div>

  
</div>